blank_issues_enabled: true
contact_links:
  - name: 💬 Home Assistant Community thread
    url: https://community.home-assistant.io/t/neverdry-smart-irrigation-that-calculates-when-and-how-long-to-water-fao-56-water-balance-hacs/1013835
    about: Setup questions and general discussion.
